// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXwoGE7xlaYfaT4koSOVWfOTE5JgrDyFs',
    appId: '1:488410388929:web:563e6874f6f68f9f8bf740',
    messagingSenderId: '488410388929',
    projectId: 'student-app-5d3f6',
    authDomain: 'student-app-5d3f6.firebaseapp.com',
    storageBucket: 'student-app-5d3f6.firebasestorage.app',
    measurementId: 'G-QFRESNB3X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ZQEjCTqkEm3JjRdzpNu2o6WoRtYAguk',
    appId: '1:488410388929:android:f0ccb26dba52a37b8bf740',
    messagingSenderId: '488410388929',
    projectId: 'student-app-5d3f6',
    storageBucket: 'student-app-5d3f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRMHqLREYyNOK4Fz5QCGG7QNbNYK3ULw4',
    appId: '1:488410388929:ios:39f656947735cdc38bf740',
    messagingSenderId: '488410388929',
    projectId: 'student-app-5d3f6',
    storageBucket: 'student-app-5d3f6.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRMHqLREYyNOK4Fz5QCGG7QNbNYK3ULw4',
    appId: '1:488410388929:ios:39f656947735cdc38bf740',
    messagingSenderId: '488410388929',
    projectId: 'student-app-5d3f6',
    storageBucket: 'student-app-5d3f6.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXwoGE7xlaYfaT4koSOVWfOTE5JgrDyFs',
    appId: '1:488410388929:web:e411303e293ebc578bf740',
    messagingSenderId: '488410388929',
    projectId: 'student-app-5d3f6',
    authDomain: 'student-app-5d3f6.firebaseapp.com',
    storageBucket: 'student-app-5d3f6.firebasestorage.app',
    measurementId: 'G-55K7FR990T',
  );
}
